name: LegacyPortalPlugin
main: com.epochmc.portalpluginlegacy.PortalPlugin
version: 1.0-LEGACY
authors:
  - dotblank (original author)
  - HACKhalo2 (original maintainer)
  - LukeFlynn (partial rewrite)
